project:
  type: website

website:
  title: "Ferrari GK"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - href: intro.qmd
      #   text: Intro & Background
      # - href: reqnspecs.qmd
      #   text: Requirements & Specs
      - href: designfeatures.qmd
        text: Subsystems Design Features 
      - href: evaluationofdesign.qmd
        text: Evaluation
      - href: references.qmd
        text: References
      # - href: futurework.qmd
      #   text: Future Work
      # - href: conclusions.qmd
      #   text: Conclusions

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



