project:
  type: website

website:
  title: "Vehicle 1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro.qmd
        text: Intro & Background
      - href: reqnspecs.qmd
        text: Requirements & Specs
      - href: designfeatures.qmd
        text: Design Features of Main Subsystems
      - href: evaluationofdesign.qmd
        text: Evaluation of Design
      - href: futurework.qmd
        text: Future Work
      - href: conclusions.qmd
        text: Conclusions

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



