---
title: "About"
---

## Victoria Parizot
Victoria Parizot is interested with mechanical and electrical design, and excited to be taking Mech Design this semester! At Harvey Mudd, she is a West Dorm President, a Machine Shop Proctor, and a Member of the Tau Beta Pi Honors Society. In her free time, she enjoys woodworking, taking and developing film photos, and sailing.

## Audrey Vo
Audrey is an APISPAM Head Sponsor, Atwood Dorm President, and Machine Shop Proctor at Harvey Mudd. The past few summers, she has been able to participate in summer research with Prof. Dodds in “Summer Start-Up” and with Prof. Gokli as part of the Riggs Fellowship. She was previously HMC 2025 Class President and also a member of the Prisoner Education Project.

Audrey is currently a resident of Southern California, and have lived here her entire life. If you have any recommendations of things to do in CA, please let her know! In her free time, she love to play pickleball, try new foods, and spend time with friends.

## Ahlyssa Santillana 


## Alina Scholz
Alina is interested in systems and dynamics engineering, especially in aerospace and biomedical fields. She's a machine shop proctor, member of Tau Beta Pi honor society, and member of SWE! 

## Sid Tchanyoum
Sid is the NSBE Outreach Coordinator and BLAM Social Media Chair. She is interested in mechanical and acoustical engineering, and has really enjoyed being a part of both Prof Mendelson's Mech Design and FILM Lab. She enjoys filmmaking, photography, and watching basketball.
